# Generated by Django 5.0.7 on 2024-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_ats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordedvideo",
            name="duration",
            field=models.DurationField(),
        ),
    ]
